### ISSUE TITLE
does this work with arrays of NSManagedObjects?

### ISSUE THREAD

**Issue by haemi** [Wondermall/Doppelganger#2]
because overriding isEqual: isn't allowed there...

**Comment by zats** [comment]
Overriding `isEqual:` is not a requirement, the default `-[NSObject isEqual:]` compares pointers and that alone should be enough (unless you require custom logic), `NSManagedObject` is not an exception.

But, as, I'm sure, you know, there is `NSFetchedResultsController` that works especially well with CoreData's models, is there any particular reason why you don't want to use it instead?

If you do try Doppelganger with `NSManagedObject`, please, feel free to share your findings.

**Comment by zats** [comment]
I'm closing this one as it doesn't seem to be active
